podTemplate(
  label: "python-builder",
  // Keep docker container started for 10 minutes before deleting it
  idleMinutes: 10,
  // Affect service account to update develop
  serviceAccount: 'default',
  // Uncomment to use secret to pull secret image
  // imagePullSecrets: [ 'github-cred' ],
  // Containers to create
  containers: [
    containerTemplate(
      name: 'python',
      image: 'python:3.12-alpine3.19',
      ttyEnabled: true,
      command: 'cat',
      resourceRequestMemory: "200M",
      resourceLimitMemory: "250M"
    ),
    containerTemplate(
      name: 'kaniko',
      image: 'gcr.io/kaniko-project/executor:v1.22.0-debug',
      ttyEnabled: true,
      command: 'cat'
    ),
  ],
) {
  node("python-builder") {
    stage("checkout") {
      checkout scm
    }
    container('python') {
      stage("prereq") {
        sh("pip install -r ch3/apps/python-demo/src/requirements.txt")
        sh("pip install pylint")
      }
      stage('linter') {
        sh("pylint ch3/apps/python-demo/src/ --exit-zero")
      }
    }
    container('kaniko') {
      def imageName = "registry.localhost:5000/python-demo:"
      stage('build') {
        sh("/kaniko/executor --context ch3/apps/python-demo/src/ --destination ${imageName}${BUILD_TAG} --destination ${imageName}${env.BRANCH_NAME}")
      }
    }
  }
}
