resources:
  - deployment.yaml
  - service.yaml

namePrefix: ch3-

images:
  - name: registry.localhost:12345/python-demo:jenkins-python-demo-0
    newName: registry.localhost:12345/python-demo
    newTag: "jenkins-python-demo-3"
