---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: packt-fluxcd
servers: 1 # same as `--servers 1`
agents: 2 # same as `--agents 2`
image: docker.io/rancher/k3s:v1.27.4-k3s1
options:
  k3d: # k3d runtime settings
    disableLoadbalancer: true # same as `--no-lb`
