apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: 5.1.8
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: default
      interval: 1m
  values:
    controller:
      JCasC:
        configScripts:
          welcome-message: |
            jenkins:
              systemMessage: Welcome to our [Packt] GitOps Simplified.
